import type { InspireQuote, InspireCategory } from "@/lib/types"

export const INSPIRE_CATEGORIES: {
  id: InspireCategory
  label: string
  description: string
  image: string
}[] = [
  { id: "stoic", label: "Stoic Philosophy", description: "Timeless wisdom on resilience, virtue, and inner strength", image: "/images/inspire/cat-stoic.jpg" },
  { id: "poetry", label: "Poetry & Literature", description: "Beautiful words from the world's greatest writers", image: "/images/inspire/cat-poetry.jpg" },
  { id: "entrepreneurship", label: "Entrepreneurship & Hustle", description: "Bold words for builders, dreamers, and doers", image: "/images/inspire/cat-entrepreneurship.jpg" },
  { id: "mindfulness", label: "Mindfulness & Calm", description: "Gentle reminders to breathe, be present, and find peace", image: "/images/inspire/cat-mindfulness.jpg" },
  { id: "leadership", label: "Leadership & Courage", description: "Words that forge character and inspire action", image: "/images/inspire/cat-leadership.jpg" },
  { id: "love", label: "Love & Connection", description: "The language of the heart from poets and romantics", image: "/images/inspire/cat-love.jpg" },
]

export const INSPIRE_QUOTES: InspireQuote[] = [
  // ── Stoic Philosophy ──
  {
    id: "q-1",
    text: "The happiness of your life depends upon the quality of your thoughts.",
    author: "Marcus Aurelius",
    authorTitle: "Roman Emperor & Philosopher",
    category: "stoic",
    tags: ["happiness", "mindset", "thoughts"],
  },
  {
    id: "q-2",
    text: "We suffer more often in imagination than in reality.",
    author: "Seneca",
    authorTitle: "Stoic Philosopher",
    category: "stoic",
    tags: ["suffering", "mindset", "fear"],
  },
  {
    id: "q-3",
    text: "It is not what happens to you, but how you react to it that matters.",
    author: "Epictetus",
    authorTitle: "Stoic Philosopher",
    category: "stoic",
    tags: ["resilience", "perspective", "reaction"],
  },
  {
    id: "q-4",
    text: "Waste no more time arguing about what a good man should be. Be one.",
    author: "Marcus Aurelius",
    authorTitle: "Roman Emperor & Philosopher",
    category: "stoic",
    tags: ["action", "character", "virtue"],
  },
  {
    id: "q-5",
    text: "He who fears death will never do anything worthy of a man who is alive.",
    author: "Seneca",
    authorTitle: "Stoic Philosopher",
    category: "stoic",
    tags: ["courage", "fear", "living"],
  },
  {
    id: "q-6",
    text: "The soul becomes dyed with the colour of its thoughts.",
    author: "Marcus Aurelius",
    authorTitle: "Roman Emperor & Philosopher",
    category: "stoic",
    tags: ["thoughts", "character", "mindset"],
  },
  {
    id: "q-7",
    text: "Difficulty shows what men are.",
    author: "Epictetus",
    authorTitle: "Stoic Philosopher",
    category: "stoic",
    tags: ["adversity", "character", "strength"],
  },
  {
    id: "q-8",
    text: "Begin at once to live, and count each separate day as a separate life.",
    author: "Seneca",
    authorTitle: "Stoic Philosopher",
    category: "stoic",
    tags: ["present", "living", "mindfulness"],
  },

  // ── Poetry & Literature ──
  {
    id: "q-9",
    text: "What you seek is seeking you.",
    author: "Rumi",
    authorTitle: "Persian Poet",
    category: "poetry",
    tags: ["purpose", "destiny", "seeking"],
  },
  {
    id: "q-10",
    text: "We delight in the beauty of the butterfly, but rarely admit the changes it has gone through to achieve that beauty.",
    author: "Maya Angelou",
    authorTitle: "Poet & Civil Rights Activist",
    category: "poetry",
    tags: ["growth", "beauty", "transformation"],
  },
  {
    id: "q-11",
    text: "To live is the rarest thing in the world. Most people exist, that is all.",
    author: "Oscar Wilde",
    authorTitle: "Playwright & Poet",
    category: "poetry",
    tags: ["living", "existence", "rare"],
  },
  {
    id: "q-12",
    text: "Do not go where the path may lead, go instead where there is no path and leave a trail.",
    author: "Ralph Waldo Emerson",
    authorTitle: "Essayist & Philosopher",
    category: "poetry",
    tags: ["path", "individuality", "courage"],
  },
  {
    id: "q-13",
    text: "The wound is the place where the Light enters you.",
    author: "Rumi",
    authorTitle: "Persian Poet",
    category: "poetry",
    tags: ["healing", "pain", "light"],
  },
  {
    id: "q-14",
    text: "Tell me, what is it you plan to do with your one wild and precious life?",
    author: "Mary Oliver",
    authorTitle: "Poet",
    category: "poetry",
    tags: ["life", "purpose", "passion"],
  },
  {
    id: "q-15",
    text: "I am not what happened to me. I am what I choose to become.",
    author: "Carl Jung",
    authorTitle: "Psychologist & Author",
    category: "poetry",
    tags: ["identity", "choice", "becoming"],
  },
  {
    id: "q-16",
    text: "The only way to deal with an unfree world is to become so absolutely free that your very existence is an act of rebellion.",
    author: "Albert Camus",
    authorTitle: "Philosopher & Author",
    category: "poetry",
    tags: ["freedom", "rebellion", "existence"],
  },

  // ── Entrepreneurship & Hustle ──
  {
    id: "q-17",
    text: "Stay hungry. Stay foolish.",
    author: "Steve Jobs",
    authorTitle: "Co-Founder, Apple",
    category: "entrepreneurship",
    tags: ["ambition", "curiosity", "hustle"],
  },
  {
    id: "q-18",
    text: "The only way to do great work is to love what you do.",
    author: "Steve Jobs",
    authorTitle: "Co-Founder, Apple",
    category: "entrepreneurship",
    tags: ["passion", "work", "greatness"],
  },
  {
    id: "q-19",
    text: "A ship in harbor is safe, but that is not what ships are built for.",
    author: "John A. Shedd",
    authorTitle: "Author",
    category: "entrepreneurship",
    tags: ["risk", "courage", "purpose"],
  },
  {
    id: "q-20",
    text: "In order to be irreplaceable one must always be different.",
    author: "Coco Chanel",
    authorTitle: "Fashion Designer",
    category: "entrepreneurship",
    tags: ["uniqueness", "individuality", "excellence"],
  },
  {
    id: "q-21",
    text: "Desire is a contract you make with yourself to be unhappy until you get what you want.",
    author: "Naval Ravikant",
    authorTitle: "Entrepreneur & Philosopher",
    category: "entrepreneurship",
    tags: ["desire", "contentment", "wisdom"],
  },
  {
    id: "q-22",
    text: "The best time to plant a tree was 20 years ago. The second best time is now.",
    author: "Chinese Proverb",
    authorTitle: "Traditional Wisdom",
    category: "entrepreneurship",
    tags: ["action", "timing", "beginnings"],
  },
  {
    id: "q-23",
    text: "Work hard in silence. Let success be your noise.",
    author: "Frank Ocean",
    authorTitle: "Artist & Musician",
    category: "entrepreneurship",
    tags: ["hustle", "success", "humility"],
  },
  {
    id: "q-24",
    text: "I have not failed. I have just found 10,000 ways that won't work.",
    author: "Thomas Edison",
    authorTitle: "Inventor",
    category: "entrepreneurship",
    tags: ["failure", "persistence", "innovation"],
  },

  // ── Mindfulness & Calm ──
  {
    id: "q-25",
    text: "The present moment is filled with joy and happiness. If you are attentive, you will see it.",
    author: "Thich Nhat Hanh",
    authorTitle: "Zen Buddhist Monk",
    category: "mindfulness",
    tags: ["presence", "joy", "attention"],
  },
  {
    id: "q-26",
    text: "Nature does not hurry, yet everything is accomplished.",
    author: "Lao Tzu",
    authorTitle: "Philosopher",
    category: "mindfulness",
    tags: ["patience", "nature", "flow"],
  },
  {
    id: "q-27",
    text: "Peace comes from within. Do not seek it without.",
    author: "Buddha",
    authorTitle: "Spiritual Teacher",
    category: "mindfulness",
    tags: ["peace", "inner", "seeking"],
  },
  {
    id: "q-28",
    text: "The quieter you become, the more you can hear.",
    author: "Rumi",
    authorTitle: "Persian Poet",
    category: "mindfulness",
    tags: ["silence", "listening", "awareness"],
  },
  {
    id: "q-29",
    text: "Almost everything will work again if you unplug it for a few minutes, including you.",
    author: "Anne Lamott",
    authorTitle: "Author",
    category: "mindfulness",
    tags: ["rest", "reset", "self-care"],
  },
  {
    id: "q-30",
    text: "Be where you are, not where you think you should be.",
    author: "Unknown",
    authorTitle: "",
    category: "mindfulness",
    tags: ["presence", "acceptance", "now"],
  },
  {
    id: "q-31",
    text: "In the midst of movement and chaos, keep stillness inside of you.",
    author: "Deepak Chopra",
    authorTitle: "Author & Speaker",
    category: "mindfulness",
    tags: ["stillness", "chaos", "inner peace"],
  },
  {
    id: "q-32",
    text: "Breathe. Let go. And remind yourself that this very moment is the only one you know you have for sure.",
    author: "Oprah Winfrey",
    authorTitle: "Media Leader & Philanthropist",
    category: "mindfulness",
    tags: ["breathing", "letting go", "present"],
  },

  // ── Leadership & Courage ──
  {
    id: "q-33",
    text: "It always seems impossible until it is done.",
    author: "Nelson Mandela",
    authorTitle: "Former President of South Africa",
    category: "leadership",
    tags: ["perseverance", "impossible", "achievement"],
  },
  {
    id: "q-34",
    text: "It is not the critic who counts; not the man who points out how the strong man stumbles. The credit belongs to the man who is actually in the arena.",
    author: "Theodore Roosevelt",
    authorTitle: "26th President of the United States",
    category: "leadership",
    tags: ["courage", "arena", "action"],
  },
  {
    id: "q-35",
    text: "Courage is not the absence of fear, but the triumph over it.",
    author: "Nelson Mandela",
    authorTitle: "Former President of South Africa",
    category: "leadership",
    tags: ["courage", "fear", "triumph"],
  },
  {
    id: "q-36",
    text: "Success is not final, failure is not fatal: it is the courage to continue that counts.",
    author: "Winston Churchill",
    authorTitle: "Former Prime Minister of the United Kingdom",
    category: "leadership",
    tags: ["success", "failure", "courage"],
  },
  {
    id: "q-37",
    text: "Vulnerability is not winning or losing; it is having the courage to show up and be seen.",
    author: "Brene Brown",
    authorTitle: "Researcher & Author",
    category: "leadership",
    tags: ["vulnerability", "courage", "authenticity"],
  },
  {
    id: "q-38",
    text: "The ultimate measure of a man is not where he stands in moments of comfort, but where he stands at times of challenge.",
    author: "Martin Luther King Jr.",
    authorTitle: "Civil Rights Leader",
    category: "leadership",
    tags: ["character", "challenge", "measure"],
  },
  {
    id: "q-39",
    text: "Do what you feel in your heart to be right, for you will be criticized anyway.",
    author: "Eleanor Roosevelt",
    authorTitle: "Former First Lady",
    category: "leadership",
    tags: ["conviction", "criticism", "heart"],
  },
  {
    id: "q-40",
    text: "A leader is one who knows the way, goes the way, and shows the way.",
    author: "John C. Maxwell",
    authorTitle: "Author & Speaker",
    category: "leadership",
    tags: ["leadership", "example", "guidance"],
  },

  // ── Love & Connection ──
  {
    id: "q-41",
    text: "Let yourself be silently drawn by the strange pull of what you really love. It will not lead you astray.",
    author: "Rumi",
    authorTitle: "Persian Poet",
    category: "love",
    tags: ["love", "passion", "following"],
  },
  {
    id: "q-42",
    text: "Your task is not to seek for love, but merely to seek and find all the barriers within yourself that you have built against it.",
    author: "Rumi",
    authorTitle: "Persian Poet",
    category: "love",
    tags: ["love", "barriers", "self-discovery"],
  },
  {
    id: "q-43",
    text: "You yourself, as much as anybody in the entire universe, deserve your love and affection.",
    author: "Buddha",
    authorTitle: "Spiritual Teacher",
    category: "love",
    tags: ["self-love", "worthiness", "compassion"],
  },
  {
    id: "q-44",
    text: "Where there is love there is life.",
    author: "Mahatma Gandhi",
    authorTitle: "Activist & Leader",
    category: "love",
    tags: ["love", "life", "connection"],
  },
  {
    id: "q-45",
    text: "Love is not something you go out and look for. Love finds you, and when it does, ready or not, it will be the best thing to ever happen to you.",
    author: "Unknown",
    authorTitle: "",
    category: "love",
    tags: ["love", "fate", "readiness"],
  },
  {
    id: "q-46",
    text: "I love you not because of who you are, but because of who I am when I am with you.",
    author: "Roy Croft",
    authorTitle: "Poet",
    category: "love",
    tags: ["love", "identity", "together"],
  },
  {
    id: "q-47",
    text: "And in the end, the love you take is equal to the love you make.",
    author: "Paul McCartney",
    authorTitle: "Musician & Songwriter",
    category: "love",
    tags: ["love", "giving", "balance"],
  },
  {
    id: "q-48",
    text: "To love and be loved is to feel the sun from both sides.",
    author: "David Viscott",
    authorTitle: "Author & Psychiatrist",
    category: "love",
    tags: ["love", "warmth", "reciprocity"],
  },
]
